Fix hotReload example
Webpack gave me an error when I tried the hotReload example:

```
Error: options/query provided without loader (use loader + options) in {
  "test": {},
  "exclude": {},
  "use": [
    "svelte-loader"
  ],
  "options": {
    "hotReload": true
  }
}
```

I've fixed it so it'll work, with `loader` and `options` inside a `use` block.